# Site settings
title: UBOS - The Linux Distro for Home Servers and Indie IoT Devices
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ubos.net" # the base hostname & protocol for your site
twitter_username: uboslinux
github_username:  uboslinux

permalink: /blog/:year/:month/:day/:title.html
paginate: 10
paginate_path: "/blog/archive:num/"

# Build settings
markdown: kramdown

# From https://raw.githubusercontent.com/recurser/jekyll-plugins/master/generate_categories.rb
category_dir:  tags
category_title_prefix: 'Tag: '

plugins: [jekyll-paginate]

